# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "hello-world-jware-terraform-state"
    dynamodb_table = "tf-locks"
    encrypt        = true
    key            = "./tf.tfstate"
    region         = "us-east-2"
  }
}
