# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "jknsware-hello-world"
    workspaces {
      prefix = "hello-world-"
    }
  }
}
